import {
  TrendingUp,
  Eye,
  FileSearch,
  GitCompare,
  Link2,
  FileText,
  FileSpreadsheet,
  ImageIcon,
  BookOpen,
  Gauge,
  FileCode,
  AlignLeft,
  RefreshCw,
  MousePointerClick,
  BarChart3,
  Code2,
  LayoutTemplate,
  Activity,
  MapPin,
} from 'lucide-react'

import type { ToolCategory, ToolManifest } from './types'

export const TOOLS: ToolManifest[] = [
  // ── Existing tools ────────────────────────────────────────────────────────

  {
    slug: 'keyword-quick-wins',
    name: 'Keyword Quick Wins',
    description: 'Find keywords ranking positions 4–20 with high impressions. The easiest clicks you are leaving on the table.',
    icon: TrendingUp,
    category: 'analyze',
    tags: ['keywords', 'gsc', 'positions'],
    inputType: 'client',
    dataSources: ['gsc'],
    access: 'admin',
    status: 'stable',
    persistsRuns: false,
    estimatedRuntime: 'fast',
    route: '/tools/keyword-quick-wins',
  },
  {
    slug: 'ai-visibility',
    name: 'AI Visibility Check',
    description: 'Measure branded vs. non-branded search share. See whether AI referral traffic is building brand recognition.',
    icon: Eye,
    category: 'analyze',
    tags: ['ai', 'branded', 'search-share'],
    inputType: 'client',
    dataSources: ['gsc', 'ga4'],
    access: 'admin',
    status: 'stable',
    persistsRuns: false,
    estimatedRuntime: 'fast',
    route: '/tools/ai-visibility',
  },
  {
    slug: 'content-gaps',
    name: 'Content Gap Finder',
    description: 'Surface high-impression queries with low CTR or poor rankings — pages that need copy, title, or structural work.',
    icon: FileSearch,
    category: 'analyze',
    tags: ['content', 'ctr', 'rankings'],
    inputType: 'client',
    dataSources: ['gsc'],
    access: 'admin',
    status: 'stable',
    persistsRuns: false,
    estimatedRuntime: 'fast',
    route: '/tools/content-gaps',
  },
  {
    slug: 'semrush-gap',
    name: 'Competitor Gap Analysis',
    description: "Find keywords competitors rank for that your client doesn't. Filter by blog, product, service, or location pages.",
    icon: GitCompare,
    category: 'analyze',
    tags: ['competitors', 'keywords', 'semrush'],
    inputType: 'client',
    dataSources: ['semrush'],
    access: 'admin',
    status: 'stable',
    persistsRuns: false,
    estimatedRuntime: 'medium',
    route: '/tools/semrush-gap',
  },
  {
    slug: 'backlink-overview',
    name: 'Backlink Overview',
    description: 'View domain authority, organic traffic, backlink count, and referring domains via Semrush.',
    icon: Link2,
    category: 'research',
    tags: ['backlinks', 'authority', 'semrush'],
    inputType: 'client',
    dataSources: ['semrush'],
    access: 'admin',
    status: 'stable',
    persistsRuns: false,
    estimatedRuntime: 'fast',
    route: '/tools/backlink-overview',
  },
  {
    slug: 'seo-content-engine',
    name: 'SEO Content Engine',
    description: 'Full pipeline: keyword research → content brief → draft article → DOCX export. Run multiple topics in parallel.',
    icon: FileText,
    category: 'create',
    tags: ['content', 'brief', 'docx', 'pipeline'],
    inputType: 'client',
    dataSources: ['gsc', 'semrush', 'claude', 'keywords-everywhere'],
    access: 'admin',
    status: 'stable',
    persistsRuns: true,
    estimatedRuntime: 'background',
    route: '/tools/seo-content-engine',
  },
  {
    slug: 'tfk-generator',
    name: 'TFK Page Generator',
    description: 'Generate ACF-ready location page copy for all True Food Kitchen stores via Google Places + Claude.',
    icon: FileSpreadsheet,
    category: 'create',
    tags: ['location-pages', 'acf', 'tfk'],
    inputType: 'file',
    dataSources: ['claude', 'google-places'],
    access: 'admin',
    status: 'stable',
    persistsRuns: true,
    estimatedRuntime: 'background',
    route: '/tools/tfk-generator',
  },
  {
    slug: 'blog-image-generator',
    name: 'Blog Image Generator',
    description: 'Upload a CSV or TSV of post titles and prompts. Generates 1500×1000 WebP images via OpenAI and bundles them into a ZIP.',
    icon: ImageIcon,
    category: 'create',
    tags: ['images', 'webp', 'zip'],
    inputType: 'file',
    dataSources: ['claude'],
    access: 'admin',
    status: 'stable',
    persistsRuns: true,
    estimatedRuntime: 'background',
    route: '/tools/blog-image-generator',
  },
  {
    slug: 'keyword-research',
    name: 'Keyword Research',
    description: 'Get search volume, CPC, competition, and 12-month trend data for up to 100 keywords via Keywords Everywhere.',
    icon: BookOpen,
    category: 'research',
    tags: ['volume', 'cpc', 'competition', 'trends'],
    inputType: 'keyword',
    dataSources: ['keywords-everywhere'],
    access: 'admin',
    status: 'stable',
    persistsRuns: false,
    estimatedRuntime: 'fast',
    route: '/tools/keyword-research',
  },
  {
    slug: 'core-web-vitals',
    name: 'Core Web Vitals',
    description: 'Measure CrUX field data (LCP, CLS, INP) and Lighthouse performance scores for any URL.',
    icon: Gauge,
    category: 'audit',
    tags: ['lcp', 'cls', 'inp', 'lighthouse'],
    inputType: 'url',
    dataSources: ['psi'],
    access: 'admin',
    status: 'stable',
    persistsRuns: false,
    estimatedRuntime: 'fast',
    route: '/tools/core-web-vitals',
  },
  {
    slug: 'page-seo-audit',
    name: 'Page SEO Audit',
    description: 'Crawl a page and check title, meta description, headings, images, structured data, and canonical tags.',
    icon: FileCode,
    category: 'audit',
    tags: ['meta', 'headings', 'schema', 'canonical'],
    inputType: 'url',
    dataSources: ['psi', 'claude'],
    access: 'admin',
    status: 'stable',
    persistsRuns: false,
    estimatedRuntime: 'medium',
    route: '/tools/page-seo-audit',
  },
  {
    slug: 'content-quality',
    name: 'Content Quality',
    description: 'Analyze word count, reading level, heading structure, image alt coverage, and internal linking density.',
    icon: AlignLeft,
    category: 'audit',
    tags: ['readability', 'word-count', 'headings', 'alt-text'],
    inputType: 'url',
    dataSources: ['claude'],
    access: 'admin',
    status: 'stable',
    persistsRuns: false,
    estimatedRuntime: 'medium',
    route: '/tools/content-quality',
  },

  // ── New tools ─────────────────────────────────────────────────────────────

  {
    slug: 'content-refresh-finder',
    name: 'Content Refresh Finder',
    description: 'Identify pages with declining GSC traffic and AI-generated refresh briefs. One-click send to Content Engine.',
    icon: RefreshCw,
    category: 'analyze',
    tags: ['refresh', 'decay', 'content-engine'],
    inputType: 'client',
    dataSources: ['gsc', 'ga4', 'claude'],
    access: 'admin',
    status: 'new',
    persistsRuns: true,
    estimatedRuntime: 'slow',
    route: '/tools/content-refresh-finder',
  },
  {
    slug: 'landing-page-cro-audit',
    name: 'Landing Page CRO Audit',
    description: 'Score any landing page on form friction, CTA clarity, trust signals, and page speed. Track improvements over time.',
    icon: MousePointerClick,
    category: 'audit',
    tags: ['cro', 'conversion', 'cta', 'ux'],
    inputType: 'url',
    dataSources: ['psi', 'claude'],
    access: 'admin',
    status: 'new',
    persistsRuns: true,
    estimatedRuntime: 'medium',
    route: '/tools/landing-page-cro-audit',
  },
  {
    slug: 'vertical-benchmark',
    name: 'Vertical Benchmark',
    description: "Research best-in-class sites in your client's vertical. Extract SEO + GEO patterns and run citation probing against top LLMs.",
    icon: BarChart3,
    category: 'research',
    tags: ['benchmark', 'geo', 'geo', 'competitors', 'vertical'],
    inputType: 'mixed',
    dataSources: ['semrush', 'claude', 'psi'],
    access: 'admin',
    status: 'new',
    persistsRuns: true,
    estimatedRuntime: 'background',
    route: '/tools/vertical-benchmark',
  },
  {
    slug: 'schema-generator',
    name: 'Schema Markup Generator',
    description: 'Generate and validate JSON-LD schema markup — LocalBusiness, Service, FAQ, HowTo, Review. Home-services templates included.',
    icon: Code2,
    category: 'create',
    tags: ['schema', 'json-ld', 'structured-data', 'local-business'],
    inputType: 'url',
    dataSources: ['claude', 'psi'],
    access: 'admin',
    status: 'coming-soon',
    persistsRuns: true,
    estimatedRuntime: 'fast',
    route: '/tools/schema-generator',
  },
  {
    slug: 'service-page-generator',
    name: 'Service Page Generator',
    description: 'Generate a service × location matrix of SEO-optimized pages with local modifiers. DOCX output, bulk ZIP download.',
    icon: LayoutTemplate,
    category: 'create',
    tags: ['service-pages', 'local', 'docx', 'home-services'],
    inputType: 'client',
    dataSources: ['claude', 'google-places'],
    access: 'admin',
    status: 'coming-soon',
    persistsRuns: true,
    estimatedRuntime: 'background',
    route: '/tools/service-page-generator',
  },
  {
    slug: 'indexation-monitor',
    name: 'Indexation Monitor',
    description: 'Track indexed page counts daily, surface coverage issues, and alert on sudden drops or discovered-but-not-indexed growth.',
    icon: Activity,
    category: 'monitor',
    tags: ['indexation', 'coverage', 'alerts', 'scheduled'],
    inputType: 'client',
    dataSources: ['gsc'],
    access: 'admin',
    status: 'coming-soon',
    persistsRuns: true,
    estimatedRuntime: 'slow',
    route: '/tools/indexation-monitor',
  },
  {
    slug: 'gbp-audit',
    name: 'GBP Audit',
    description: 'Audit all Google Business Profile locations for NAP consistency, phone, website, hours, category, and description completeness.',
    icon: MapPin,
    category: 'audit',
    tags: ['google-business', 'nap', 'locations', 'completeness'],
    inputType: 'client',
    dataSources: ['gbp'],
    access: 'admin',
    status: 'new',
    persistsRuns: true,
    estimatedRuntime: 'slow',
    route: '/tools/gbp-audit',
  },
]

export function getToolBySlug(slug: string): ToolManifest | undefined {
  return TOOLS.find((tool) => tool.slug === slug)
}

export function getToolsByCategory(category: ToolCategory): ToolManifest[] {
  return TOOLS.filter((tool) => tool.category === category)
}
